#!/bin/sh

do_git() {
	git rev-parse --git-dir 1> /dev/null 2>&1 \
	&& git add $1 \
	&& printf "Auto-commit of $1 by diary script\n" | git commit $1 -F - 
}

changed() {
	prepend_date $1 $3
	if diff "$2" "$3" >/dev/null 2>&1 ; then
		rm $2
		rm $3
		return 1
	else
		mv $2 $1
		rm $3
		return 0
	fi
}

prepend_date() {
	printf "$date\n\n" | cat - $1 > $2
}

safety() {
	if test -f "$1"; then
		cat <<-EOF 1>&2
		Swap file "$1" already exists! Aborting...
		EOF
		return 1
	fi
}

main() {
	readonly date="$(date +"%a,%e %b %G %H:%M:%S %z")"
	readonly diary=.log
	readonly swap=.swp
	readonly swapfile=$diary$swap
	readonly diff=.diff
	readonly difffile=$diary$diff

	safety $swapfile || return 1
	safety $difffile || return 1
	test -w $diary || touch $diary || return 1

	prepend_date $diary $swapfile
	${EDITOR:-vi} $swapfile
	if changed $diary $swapfile $difffile ; then
		do_git $diary
	fi
}
main
