#!/bin/sh

do_git() {
	git rev-parse --git-dir 1> /dev/null 2>&1 \
	&& git add "$1" \
	&& echo "Auto-commit of $1 by diary script" | git commit "$1" -F -
}

safety() {
	if test -e "$1"; then
		echo "Swap file $1 already exists! Aborting..." 1>&2
		return 1
	fi
}

main() {
	readonly local date="$(date +"%a,%e %b %G %H:%M:%S %z")"
	readonly local diary=.log
	readonly local swap=${diary}.swp
	readonly local diff=${diary}.diff

	safety "$swap" || return 1
	safety "$diff" || return 1
	test -w "$diary" || touch "$diary" || return 1

	printf "%s\n\n" "$date" | cat - "$diary" | tee "$diff" > "$swap"
	${EDITOR:-vi} "$swap"
	if diff "$swap" "$diff" >/dev/null 2>&1 ; then
		rm "$swap"
		rm "$diff"
	else
		mv "$swap" "$diary"
		rm "$diff"
		do_git "$diary"
	fi
}
main
