#!/bin/sh

do_git() {
	git rev-parse --git-dir 1> /dev/null 2>&1 \
	&& git add "$1" \
	&& echo "Auto-commit of $1 by diary script" | git commit "$1" -F -
}

safety() {
	if test -e "$1"; then
		echo "Swap file $1 already exists." 1>&2
		return 1
	fi
}

main() {
	readonly local date="$(date +"%a,%e %b %G %H:%M:%S %z")"
	readonly local diary=.log
	readonly local swap=${diary}.swp
	readonly local diff=${diary}.diff
	readonly local editor=${EDITOR:-vi}

	safety "$swap" || { echo "Aborting!" 1>&2; return 1; }
	safety "$diff" || { echo "Aborting!" 1>&2; return 1; }
	test -w "$diary" || touch "$diary" || return 1

	if test "X$1" = "X-" ; then # read input from stdin
		printf "%s\n\n" "$date" | cat - "$diary" > "$diff"
		{ cat -; printf "\n"; } \
			| { printf "%s\n" "$date"; cat - "$diary"; } > "$swap"
	else # open editor for interactive
		printf "%s\n\n" "$date" | cat - "$diary" | tee "$diff" > "$swap"
		$editor $swap
	fi
	if diff "$swap" "$diff" >/dev/null 2>&1 ; then
		rm "$swap"
		rm "$diff"
		test -s $diary || rm $diary
	else
		mv "$swap" "$diary"
		rm "$diff"
		do_git "$diary"
	fi
}
main "$@"
